baseURL = "https://bebopx.com/"
languageCode = "en-us"
title = "BebopX"
theme = "hugograyscale"

googleAnalytics = "UA-147412504-1"

[params]
    # Provide some metadata for search and indexing services
    description = "Make products people love"
    author = "BebopX"
    # author = "BernieLiu"